### ISSUE TITLE
提交审核无法选择文件

### ISSUE THREAD

**Issue by GabrielOmarBatistuta** [wg689/Solve-App-Store-Review-Problem#1]
这个不是因为在iTunesconnect后台创建应用的时候，初始默认语言选择以后，在提审的时候修改了默认语言造成的么？我遇到的是，初始默认语言设置为美英，然后提交前修改成其他语言的时候，媒体管理只能在美英状态下选择。

**Comment by wg689** [comment]
苹果工程师回复 说这个是 appstore 的bug,有些人切换语言还是不能上传,只能删除应用更换bundleID重新上传.
