### ISSUE TITLE
更改底层 ipv4 API 兼容 ipv6的方面的问题

### ISSUE THREAD

**Issue by GDMiao** [wg689/Solve-App-Store-Review-Problem#2]
我们项目中有一些网络协议是ipv4的，这个怎么才能改成ipv6的 做到兼容。

**Comment by wg689** [comment]
1)首先你需要确定是否需要修改,很多情况下是不需要修改的,QQ群有用户使用自己写的socket没有做任何修改顺利通过审核.   2)如果确定在ipv6 下面网络不通这个时候是需要修改的,这种修改需要你确定是后台不支持还是app不支持,先去测试下后台支不支持iPv6,如果不支持参考我的git让后台支持,   3)如果你的app代码不支持确认是那些地方不支持,按照我的git进行修改,一般情况下后台不支持有后台的方法,前台不支持有前台的方法, 你需要确定是前台不支持还是后台不支持,另外你用的什么协议不支持ipv6?

**Comment by GDMiao** [comment]
我在电脑测试了 在我模拟的ipv6的网络下登录都登录不了，web服务器的一些数据接口（http）是正常的，我们公司他们自己写的网络协议通信累的，我们是一个做直播的公司，登录、直播相关的都是单独的服务器（仅支持 ipv4），我工程中的一些相关协议也是 ipv4 的专有API，这个兼容我还真不会改，最近很纠结。

**Comment by wg689** [comment]
你找找6box 我的文档里面花钱买服务部分 让他们的技术人员配合你解决下
