### ISSUE TITLE
贡献一篇文章: 用手机搭建ipv6测试环境

### ISSUE THREAD

**Issue by Lafree317** [wg689/Solve-App-Store-Review-Problem#3]
贡献一篇文章: 用手机搭建ipv6测试环境:
http://gold.xitu.io/post/57c1a56d2e958a006970e448
希望能有所帮助

**Comment by wg689** [comment]
这是一篇唯一的用手机搭建ipv6 的文章很好,我自己也在用,已收录你推荐的 ,不过贴的地址是简书的,在如何搭建服务器部分.具体如何搭建ipv6测试环境参考[本地如何搭建IPv6环境测试你的APP,需要网线](http://www.jianshu.com/p/632d995749e1),[iOS-用手机网络测试Ipv6,无需网线](http://www.jianshu.com/p/6c7a155fc372)

**Comment by Lafree317** [comment]
嗯 哈哈
